package com.first1444.frc.robot2019.autonomous;

public enum AutonomousType {
	DO_NOTHING, CROSS_LINE_FORWARD, CROSS_LINE_SIDE, CENTER, OFF_CENTER, SIDE_CARGO_SHIP_CARGO, SIDE_CARGO_SHIP_HATCH, SIDE_ROCKET_HATCH
}
